/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "mcu_periph/Mockuart.h"

typedef struct _CMOCK_uart_periph_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct uart_periph* Expected_p;

} CMOCK_uart_periph_init_CALL_INSTANCE;

typedef struct _CMOCK_uart_periph_set_baudrate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct uart_periph* Expected_p;
  uint32_t Expected_baud;

} CMOCK_uart_periph_set_baudrate_CALL_INSTANCE;

typedef struct _CMOCK_uart_periph_set_bits_stop_parity_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct uart_periph* Expected_p;
  uint8_t Expected_bits;
  uint8_t Expected_stop;
  uint8_t Expected_parity;

} CMOCK_uart_periph_set_bits_stop_parity_CALL_INSTANCE;

typedef struct _CMOCK_uart_periph_set_mode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct uart_periph* Expected_p;
  bool_t Expected_tx_enabled;
  bool_t Expected_rx_enabled;
  bool_t Expected_hw_flow_control;

} CMOCK_uart_periph_set_mode_CALL_INSTANCE;

typedef struct _CMOCK_uart_transmit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct uart_periph* Expected_p;
  uint8_t Expected_data;

} CMOCK_uart_transmit_CALL_INSTANCE;

typedef struct _CMOCK_uart_check_free_space_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool_t ReturnVal;
  struct uart_periph* Expected_p;
  uint8_t Expected_len;

} CMOCK_uart_check_free_space_CALL_INSTANCE;

typedef struct _CMOCK_uart_getch_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  struct uart_periph* Expected_p;

} CMOCK_uart_getch_CALL_INSTANCE;

typedef struct _CMOCK_uart_event_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_uart_event_CALL_INSTANCE;

typedef struct _CMOCK_uart_char_available_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  struct uart_periph* Expected_p;

} CMOCK_uart_char_available_CALL_INSTANCE;

typedef struct _CMOCK_uart0_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_uart0_init_CALL_INSTANCE;

typedef struct _CMOCK_uart1_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_uart1_init_CALL_INSTANCE;

typedef struct _CMOCK_uart2_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_uart2_init_CALL_INSTANCE;

typedef struct _CMOCK_uart3_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_uart3_init_CALL_INSTANCE;

typedef struct _CMOCK_uart4_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_uart4_init_CALL_INSTANCE;

typedef struct _CMOCK_uart5_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_uart5_init_CALL_INSTANCE;

typedef struct _CMOCK_uart6_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_uart6_init_CALL_INSTANCE;

static struct MockuartInstance
{
  CMOCK_MEM_INDEX_TYPE uart_periph_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_periph_set_baudrate_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_periph_set_bits_stop_parity_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_periph_set_mode_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_transmit_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_check_free_space_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_getch_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_event_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_char_available_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart0_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart1_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart2_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart3_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart4_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart5_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart6_init_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockuart_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart_periph_init_CallInstance, cmock_line, "Function 'uart_periph_init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart_periph_set_baudrate_CallInstance, cmock_line, "Function 'uart_periph_set_baudrate' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart_periph_set_bits_stop_parity_CallInstance, cmock_line, "Function 'uart_periph_set_bits_stop_parity' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart_periph_set_mode_CallInstance, cmock_line, "Function 'uart_periph_set_mode' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart_transmit_CallInstance, cmock_line, "Function 'uart_transmit' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart_check_free_space_CallInstance, cmock_line, "Function 'uart_check_free_space' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart_getch_CallInstance, cmock_line, "Function 'uart_getch' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart_event_CallInstance, cmock_line, "Function 'uart_event' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart_char_available_CallInstance, cmock_line, "Function 'uart_char_available' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart0_init_CallInstance, cmock_line, "Function 'uart0_init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart1_init_CallInstance, cmock_line, "Function 'uart1_init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart2_init_CallInstance, cmock_line, "Function 'uart2_init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart3_init_CallInstance, cmock_line, "Function 'uart3_init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart4_init_CallInstance, cmock_line, "Function 'uart4_init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart5_init_CallInstance, cmock_line, "Function 'uart5_init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.uart6_init_CallInstance, cmock_line, "Function 'uart6_init' called less times than expected.");
}

void Mockuart_Init(void)
{
  Mockuart_Destroy();
}

void Mockuart_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void uart_periph_init(struct uart_periph* p)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_periph_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_periph_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_periph_init_CallInstance);
  Mock.uart_periph_init_CallInstance = CMock_Guts_MemNext(Mock.uart_periph_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart_periph_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_p), (void*)(p), sizeof(struct uart_periph), cmock_line, "Function 'uart_periph_init' called with unexpected value for argument 'p'.");
  }
}

void CMockExpectParameters_uart_periph_init(CMOCK_uart_periph_init_CALL_INSTANCE* cmock_call_instance, struct uart_periph* p)
{
  cmock_call_instance->Expected_p = p;
}

void uart_periph_init_CMockExpect(UNITY_LINE_TYPE cmock_line, struct uart_periph* p)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_periph_init_CALL_INSTANCE));
  CMOCK_uart_periph_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_periph_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_periph_init_CallInstance = CMock_Guts_MemChain(Mock.uart_periph_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_periph_init(cmock_call_instance, p);
}

void uart_periph_set_baudrate(struct uart_periph* p, uint32_t baud)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_periph_set_baudrate_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_periph_set_baudrate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_periph_set_baudrate_CallInstance);
  Mock.uart_periph_set_baudrate_CallInstance = CMock_Guts_MemNext(Mock.uart_periph_set_baudrate_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart_periph_set_baudrate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_p), (void*)(p), sizeof(struct uart_periph), cmock_line, "Function 'uart_periph_set_baudrate' called with unexpected value for argument 'p'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_baud, baud, cmock_line, "Function 'uart_periph_set_baudrate' called with unexpected value for argument 'baud'.");
  }
}

void CMockExpectParameters_uart_periph_set_baudrate(CMOCK_uart_periph_set_baudrate_CALL_INSTANCE* cmock_call_instance, struct uart_periph* p, uint32_t baud)
{
  cmock_call_instance->Expected_p = p;
  cmock_call_instance->Expected_baud = baud;
}

void uart_periph_set_baudrate_CMockExpect(UNITY_LINE_TYPE cmock_line, struct uart_periph* p, uint32_t baud)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_periph_set_baudrate_CALL_INSTANCE));
  CMOCK_uart_periph_set_baudrate_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_periph_set_baudrate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_periph_set_baudrate_CallInstance = CMock_Guts_MemChain(Mock.uart_periph_set_baudrate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_periph_set_baudrate(cmock_call_instance, p, baud);
}

void uart_periph_set_bits_stop_parity(struct uart_periph* p, uint8_t bits, uint8_t stop, uint8_t parity)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_periph_set_bits_stop_parity_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_periph_set_bits_stop_parity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_periph_set_bits_stop_parity_CallInstance);
  Mock.uart_periph_set_bits_stop_parity_CallInstance = CMock_Guts_MemNext(Mock.uart_periph_set_bits_stop_parity_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart_periph_set_bits_stop_parity' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_p), (void*)(p), sizeof(struct uart_periph), cmock_line, "Function 'uart_periph_set_bits_stop_parity' called with unexpected value for argument 'p'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_bits, bits, cmock_line, "Function 'uart_periph_set_bits_stop_parity' called with unexpected value for argument 'bits'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_stop, stop, cmock_line, "Function 'uart_periph_set_bits_stop_parity' called with unexpected value for argument 'stop'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_parity, parity, cmock_line, "Function 'uart_periph_set_bits_stop_parity' called with unexpected value for argument 'parity'.");
  }
}

void CMockExpectParameters_uart_periph_set_bits_stop_parity(CMOCK_uart_periph_set_bits_stop_parity_CALL_INSTANCE* cmock_call_instance, struct uart_periph* p, uint8_t bits, uint8_t stop, uint8_t parity)
{
  cmock_call_instance->Expected_p = p;
  cmock_call_instance->Expected_bits = bits;
  cmock_call_instance->Expected_stop = stop;
  cmock_call_instance->Expected_parity = parity;
}

void uart_periph_set_bits_stop_parity_CMockExpect(UNITY_LINE_TYPE cmock_line, struct uart_periph* p, uint8_t bits, uint8_t stop, uint8_t parity)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_periph_set_bits_stop_parity_CALL_INSTANCE));
  CMOCK_uart_periph_set_bits_stop_parity_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_periph_set_bits_stop_parity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_periph_set_bits_stop_parity_CallInstance = CMock_Guts_MemChain(Mock.uart_periph_set_bits_stop_parity_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_periph_set_bits_stop_parity(cmock_call_instance, p, bits, stop, parity);
}

void uart_periph_set_mode(struct uart_periph* p, bool_t tx_enabled, bool_t rx_enabled, bool_t hw_flow_control)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_periph_set_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_periph_set_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_periph_set_mode_CallInstance);
  Mock.uart_periph_set_mode_CallInstance = CMock_Guts_MemNext(Mock.uart_periph_set_mode_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart_periph_set_mode' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_p), (void*)(p), sizeof(struct uart_periph), cmock_line, "Function 'uart_periph_set_mode' called with unexpected value for argument 'p'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_tx_enabled, tx_enabled, cmock_line, "Function 'uart_periph_set_mode' called with unexpected value for argument 'tx_enabled'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_rx_enabled, rx_enabled, cmock_line, "Function 'uart_periph_set_mode' called with unexpected value for argument 'rx_enabled'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_hw_flow_control, hw_flow_control, cmock_line, "Function 'uart_periph_set_mode' called with unexpected value for argument 'hw_flow_control'.");
  }
}

void CMockExpectParameters_uart_periph_set_mode(CMOCK_uart_periph_set_mode_CALL_INSTANCE* cmock_call_instance, struct uart_periph* p, bool_t tx_enabled, bool_t rx_enabled, bool_t hw_flow_control)
{
  cmock_call_instance->Expected_p = p;
  cmock_call_instance->Expected_tx_enabled = tx_enabled;
  cmock_call_instance->Expected_rx_enabled = rx_enabled;
  cmock_call_instance->Expected_hw_flow_control = hw_flow_control;
}

void uart_periph_set_mode_CMockExpect(UNITY_LINE_TYPE cmock_line, struct uart_periph* p, bool_t tx_enabled, bool_t rx_enabled, bool_t hw_flow_control)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_periph_set_mode_CALL_INSTANCE));
  CMOCK_uart_periph_set_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_periph_set_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_periph_set_mode_CallInstance = CMock_Guts_MemChain(Mock.uart_periph_set_mode_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_periph_set_mode(cmock_call_instance, p, tx_enabled, rx_enabled, hw_flow_control);
}

void uart_transmit(struct uart_periph* p, uint8_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_transmit_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_transmit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_transmit_CallInstance);
  Mock.uart_transmit_CallInstance = CMock_Guts_MemNext(Mock.uart_transmit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart_transmit' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_p), (void*)(p), sizeof(struct uart_periph), cmock_line, "Function 'uart_transmit' called with unexpected value for argument 'p'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_data, data, cmock_line, "Function 'uart_transmit' called with unexpected value for argument 'data'.");
  }
}

void CMockExpectParameters_uart_transmit(CMOCK_uart_transmit_CALL_INSTANCE* cmock_call_instance, struct uart_periph* p, uint8_t data)
{
  cmock_call_instance->Expected_p = p;
  cmock_call_instance->Expected_data = data;
}

void uart_transmit_CMockExpect(UNITY_LINE_TYPE cmock_line, struct uart_periph* p, uint8_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_transmit_CALL_INSTANCE));
  CMOCK_uart_transmit_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_transmit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_transmit_CallInstance = CMock_Guts_MemChain(Mock.uart_transmit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_transmit(cmock_call_instance, p, data);
}

bool_t uart_check_free_space(struct uart_periph* p, uint8_t len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_check_free_space_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_check_free_space_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_check_free_space_CallInstance);
  Mock.uart_check_free_space_CallInstance = CMock_Guts_MemNext(Mock.uart_check_free_space_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart_check_free_space' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_p), (void*)(p), sizeof(struct uart_periph), cmock_line, "Function 'uart_check_free_space' called with unexpected value for argument 'p'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_len, len, cmock_line, "Function 'uart_check_free_space' called with unexpected value for argument 'len'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart_check_free_space(CMOCK_uart_check_free_space_CALL_INSTANCE* cmock_call_instance, struct uart_periph* p, uint8_t len)
{
  cmock_call_instance->Expected_p = p;
  cmock_call_instance->Expected_len = len;
}

void uart_check_free_space_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct uart_periph* p, uint8_t len, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_check_free_space_CALL_INSTANCE));
  CMOCK_uart_check_free_space_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_check_free_space_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_check_free_space_CallInstance = CMock_Guts_MemChain(Mock.uart_check_free_space_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_check_free_space(cmock_call_instance, p, len);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint8_t uart_getch(struct uart_periph* p)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_getch_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_getch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_getch_CallInstance);
  Mock.uart_getch_CallInstance = CMock_Guts_MemNext(Mock.uart_getch_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart_getch' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_p), (void*)(p), sizeof(struct uart_periph), cmock_line, "Function 'uart_getch' called with unexpected value for argument 'p'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart_getch(CMOCK_uart_getch_CALL_INSTANCE* cmock_call_instance, struct uart_periph* p)
{
  cmock_call_instance->Expected_p = p;
}

void uart_getch_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct uart_periph* p, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_getch_CALL_INSTANCE));
  CMOCK_uart_getch_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_getch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_getch_CallInstance = CMock_Guts_MemChain(Mock.uart_getch_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_getch(cmock_call_instance, p);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void uart_event(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_event_CallInstance);
  Mock.uart_event_CallInstance = CMock_Guts_MemNext(Mock.uart_event_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart_event' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void uart_event_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_event_CALL_INSTANCE));
  CMOCK_uart_event_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_event_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_event_CallInstance = CMock_Guts_MemChain(Mock.uart_event_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

uint16_t uart_char_available(struct uart_periph* p)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_char_available_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_char_available_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_char_available_CallInstance);
  Mock.uart_char_available_CallInstance = CMock_Guts_MemNext(Mock.uart_char_available_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart_char_available' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_p), (void*)(p), sizeof(struct uart_periph), cmock_line, "Function 'uart_char_available' called with unexpected value for argument 'p'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart_char_available(CMOCK_uart_char_available_CALL_INSTANCE* cmock_call_instance, struct uart_periph* p)
{
  cmock_call_instance->Expected_p = p;
}

void uart_char_available_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct uart_periph* p, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_char_available_CALL_INSTANCE));
  CMOCK_uart_char_available_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_char_available_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_char_available_CallInstance = CMock_Guts_MemChain(Mock.uart_char_available_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_char_available(cmock_call_instance, p);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void uart0_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart0_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart0_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart0_init_CallInstance);
  Mock.uart0_init_CallInstance = CMock_Guts_MemNext(Mock.uart0_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart0_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void uart0_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart0_init_CALL_INSTANCE));
  CMOCK_uart0_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart0_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart0_init_CallInstance = CMock_Guts_MemChain(Mock.uart0_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void uart1_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart1_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart1_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart1_init_CallInstance);
  Mock.uart1_init_CallInstance = CMock_Guts_MemNext(Mock.uart1_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart1_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void uart1_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart1_init_CALL_INSTANCE));
  CMOCK_uart1_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart1_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart1_init_CallInstance = CMock_Guts_MemChain(Mock.uart1_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void uart2_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart2_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart2_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart2_init_CallInstance);
  Mock.uart2_init_CallInstance = CMock_Guts_MemNext(Mock.uart2_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart2_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void uart2_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart2_init_CALL_INSTANCE));
  CMOCK_uart2_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart2_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart2_init_CallInstance = CMock_Guts_MemChain(Mock.uart2_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void uart3_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart3_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart3_init_CallInstance);
  Mock.uart3_init_CallInstance = CMock_Guts_MemNext(Mock.uart3_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart3_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void uart3_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart3_init_CALL_INSTANCE));
  CMOCK_uart3_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart3_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart3_init_CallInstance = CMock_Guts_MemChain(Mock.uart3_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void uart4_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart4_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart4_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart4_init_CallInstance);
  Mock.uart4_init_CallInstance = CMock_Guts_MemNext(Mock.uart4_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart4_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void uart4_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart4_init_CALL_INSTANCE));
  CMOCK_uart4_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart4_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart4_init_CallInstance = CMock_Guts_MemChain(Mock.uart4_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void uart5_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart5_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart5_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart5_init_CallInstance);
  Mock.uart5_init_CallInstance = CMock_Guts_MemNext(Mock.uart5_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart5_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void uart5_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart5_init_CALL_INSTANCE));
  CMOCK_uart5_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart5_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart5_init_CallInstance = CMock_Guts_MemChain(Mock.uart5_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void uart6_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart6_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart6_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart6_init_CallInstance);
  Mock.uart6_init_CallInstance = CMock_Guts_MemNext(Mock.uart6_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'uart6_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void uart6_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart6_init_CALL_INSTANCE));
  CMOCK_uart6_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart6_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart6_init_CallInstance = CMock_Guts_MemChain(Mock.uart6_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

